user:
  #登录token有效时长（分钟）
  login-token-time: 10
  #允许刷新token时长，此时间内token过期可以颁发新token（分钟）
  login-allow-time: 30

server:
  port: 7896
  servlet:
    session:
      timeout: 300
    context-path: /hd
    max-http-header-size: 65536

springfox:
  documentation:
    swagger-ui:
      #swagger开关
      enabled: true

logging:
  config: classpath:log4j-hd.xml

spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      write-dates-as-timestamps: true #日期返回时间戳
  application:
    name: hd
  # 数据源配置
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/hhh?useSSL=false&serverTimezone=GMT
#    url: jdbc:mysql://39.108.142.123:3306/hhh?useSSL=false&serverTimezone=GMT
#    username: root
#    password: 111111
#    password: 51985993+H
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://175.27.187.50:5432/cjdb?useSSL=false&serverTimezone=GMT
    username: cjopr
    password: SxMmm$A~fM9wFd6#
    hikari:
      # 连接池名
      pool-name: HdDataHikari
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0表示永久存活，默认1800000（30分钟）
      max-lifetime: 1800000
      # 连接超时时间，默认30000（30秒）
      connection-timeout: 30000
      # 测试连接是否可用的查询语句
      connection-test-query: SELECT 1

mybatis-plus:
  #外部化xml配置
  #config-location: classpath:mybatis-config.xml
  #指定外部化 MyBatis Properties 配置，通过该配置可以抽离配置，实现不同环境的配置部署
  #configuration-properties: classpath:mybatis/config.properties
  #xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  #MyBaits 别名包扫描路径，通过该属性可以给包中的类注册别名
  #type-aliases-package:
  #如果配置了该属性，则仅仅会扫描路径下以该类作为父类的域对象
  #type-aliases-super-type: java.lang.Object
  #枚举类 扫描路径，如果配置了该属性，会将路径下的枚举类进行注入，让实体类字段能够简单快捷的使用枚举属性
  #type-enums-package: com.baomidou.mybatisplus.samples.quickstart.enums
  #项目启动会检查xml配置存在(只在开发时候打开)
  check-config-location: true
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: false
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: false
    #懒加载
    #aggressive-lazy-loading: true
    #NONE：不启用自动映射 PARTIAL：只对非嵌套的 resultMap 进行自动映射 FULL：对所有的 resultMap 都进行自动映射
    #auto-mapping-behavior: partial
    #NONE：不做任何处理 (默认值)WARNING：以日志的形式打印相关警告信息 FAILING：当作映射失败处理，并抛出异常和详细信息
    #auto-mapping-unknown-column-behavior: none
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      #表名下划线命名默认true
      table-underline: true
      #id类型
      id-type: auto
      #是否开启大写命名，默认不开启
      #capital-mode: false
      #逻辑已删除值,(逻辑删除下有效) 需要注入逻辑策略LogicSqlInjector 以@Bean方式注入
      logic-not-delete-value: 0
      #逻辑未删除值,(逻辑删除下有效)
      logic-delete-value: 1
      update-strategy: not_null
    mapper-locations: classpath*:/mapper/*.xml

hd:
  username: xlkjyy001
  thsPassWord: 666888
  loadConf: F://同花顺sdk//THSDataInterface_Windows//bin//x64//iFinDJava_x64.dll
  task:
    enable: false
    insertThsMemoir: 0 58 11,18,23 * * ?
    insertThsMemoirByWeek: 0 30 23 ? * WED,SUN
    insertThsBehavior: 0 50 23 * * ?
    insertThsHot: 0 55 23 * * ?